# Generated by Django 6.0.2 on 2026-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Наименование района')),
                ('min_code', models.BigIntegerField(verbose_name='Наименьший порог кода района')),
                ('max_code', models.BigIntegerField(verbose_name='Наибольший порог кода района')),
                ('work_places', models.BigIntegerField(default=0, verbose_name='Кол-во рабочих мест')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'db_table': 'vacansy_district',
            },
        ),
        migrations.CreateModel(
            name='Vacansy',
            fields=[
                ('id', models.CharField(db_column='id', max_length=256, primary_key=True, serialize=False, verbose_name='id')),
                ('stateRegionCode', models.CharField(db_column='stateRegionCode', default='Отсутствует', verbose_name='stateRegionCode')),
                ('vacancyName', models.CharField(db_column='vacancyName', default='Отсутствует', max_length=512, verbose_name='vacancyName')),
                ('codeProfessionalSphere', models.CharField(db_column='codeProfessionalSphere', default='Отсутствует', max_length=512, verbose_name='codeProfessionalSphere')),
                ('professionalSphereName', models.CharField(db_column='professionalSphereName', default='Отсутствует', max_length=512, verbose_name='professionalSphereName')),
                ('vacancyAddress', models.CharField(db_column='vacancyAddress', default='Отсутствует', max_length=512, verbose_name='vacancyAddress')),
                ('vacancyAddressAdditionalInfo', models.CharField(db_column='vacancyAddressAdditionalInfo', default='Отсутствует', max_length=512, verbose_name='vacancyAddressAdditionalInfo')),
                ('salary', models.CharField(db_column='salary', default='Отсутствует', max_length=512, verbose_name='salary')),
                ('salaryMin', models.IntegerField(db_column='salaryMin', default=0, verbose_name='salaryMin')),
                ('salaryMax', models.IntegerField(db_column='salaryMax', default=999999, verbose_name='salaryMax')),
                ('socialProtecteds', models.TextField(db_column='socialProtecteds', default='Отсутствует', verbose_name='socialProtecteds')),
                ('languageKnowledge', models.TextField(db_column='languageKnowledge', default='Отсутствует', verbose_name='languageKnowledge')),
                ('busyType', models.TextField(db_column='busyType', default='Отсутствует', verbose_name='busyType')),
                ('skills', models.TextField(db_column='skills', default='Отсутствует', verbose_name='skills')),
                ('workPlaceForeign', models.BooleanField(blank=True, db_column='workPlaceForeign', null=True, verbose_name='workPlaceForeign')),
                ('workPlaceOrdinary', models.BooleanField(blank=True, db_column='workPlaceOrdinary', null=True, verbose_name='workPlaceOrdinary')),
                ('workPlaceQuota', models.BooleanField(blank=True, db_column='workPlaceQuota', null=True, verbose_name='workPlaceQuota')),
                ('workPlaceSpecial', models.BooleanField(blank=True, db_column='workPlaceSpecial', null=True, verbose_name='workPlaceSpecial')),
                ('trainingDays', models.IntegerField(db_column='trainingDays', default=0, verbose_name='trainingDays')),
                ('shift', models.TextField(db_column='shift', default='Отсутствует', verbose_name='shift')),
                ('hardSkills', models.TextField(db_column='hardSkills', default='Отсутствует', verbose_name='hardSkills')),
                ('softSkills', models.TextField(db_column='softSkills', default='Отсутствует', verbose_name='softSkills')),
                ('experienceRequirements', models.IntegerField(db_column='experienceRequirements', default=0, verbose_name='experienceRequirements')),
                ('scheduleType', models.TextField(db_column='scheduleType', default='Отсутствует', verbose_name='scheduleType')),
                ('careerPerspective', models.BooleanField(db_column='careerPerspective', default=False, verbose_name='careerPerspective')),
                ('codeExternalSystem', models.TextField(db_column='codeExternalSystem', default='Отсутствует', verbose_name='codeExternalSystem')),
                ('needMedcard', models.TextField(db_column='needMedcard', default='Отсутствует', verbose_name='needMedcard')),
                ('sourceType', models.TextField(db_column='sourceType', default='Отсутствует', verbose_name='sourceType')),
                ('requiredDriveLicense', models.TextField(db_column='requiredDriveLicense', default='Отсутствует', verbose_name='requiredDriveLicense')),
                ('changeTime', models.TextField(db_column='changeTime', default='Отсутствует', verbose_name='changeTime')),
                ('contactPerson', models.TextField(db_column='contactPerson', default='Отсутствует', verbose_name='contactPerson')),
                ('fullCompanyName', models.TextField(db_column='fullCompanyName', default='Отсутствует', verbose_name='fullCompanyName')),
                ('companyBusinessSize', models.TextField(db_column='companyBusinessSize', default='Отсутствует', verbose_name='companyBusinessSize')),
                ('dateModify', models.TextField(db_column='dateModify', default='Отсутствует', verbose_name='dateModify')),
                ('workPlaces', models.IntegerField(db_column='workPlaces', default=1, verbose_name='workPlaces')),
                ('isUzbekistanRecruitment', models.BooleanField(db_column='isUzbekistanRecruitment', default=False, verbose_name='isUzbekistanRecruitment')),
                ('federalDistrictCode', models.IntegerField(db_column='federalDistrictCode', default=0, verbose_name='federalDistrictCode')),
                ('datePublished', models.TextField(db_column='datePublished', default='Отсутствует', verbose_name='datePublished')),
                ('accommodationCapability', models.BooleanField(db_column='accommodationCapability', default=False, verbose_name='accommodationCapability')),
                ('foreignWorkersCapability', models.BooleanField(db_column='foreignWorkersCapability', default=False, verbose_name='foreignWorkersCapability')),
                ('isQuoted', models.BooleanField(db_column='isQuoted', default=False, verbose_name='isQuoted')),
                ('creationDate', models.TextField(db_column='creationDate', default='Отсутствует', verbose_name='creationDate')),
                ('responsibilities', models.TextField(db_column='responsibilities', default='Отсутствует', verbose_name='responsibilities')),
                ('addressCode', models.BigIntegerField(db_column='addressCode', default=0, verbose_name='addressCode')),
                ('regionName', models.TextField(db_column='regionName', default='Отсутствует', verbose_name='regionName')),
                ('status', models.TextField(db_column='status', default='Отсутствует', verbose_name='status')),
                ('vacancyUrl', models.TextField(db_column='vacancyUrl', default='Отсутствует', verbose_name='vacancyUrl')),
                ('latitude', models.FloatField(blank=True, db_column='latitude', default=0.0, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, db_column='longitude', default=0.0, null=True, verbose_name='longitude')),
                ('educationType', models.TextField(blank=True, db_column='educationType', default='Отсутствует', null=True, verbose_name='educationType')),
                ('companyCode', models.TextField(db_column='companyCode', default='Отсутствует', verbose_name='companyCode')),
                ('url', models.TextField(db_column='url', default='Отсутствует', verbose_name='url')),
                ('inn', models.TextField(db_column='inn', default='Отсутствует', verbose_name='inn')),
                ('kpp', models.TextField(db_column='kpp', default='Отсутствует', verbose_name='kpp')),
                ('ogrn', models.TextField(db_column='ogrn', default='Отсутствует', verbose_name='ogrn')),
                ('deleted', models.BooleanField(blank=True, db_column='deleted', null=True, verbose_name='deleted')),
                ('visibility', models.TextField(blank=True, db_column='visibility', default='Отсутствует', null=True, verbose_name='visibility')),
                ('contactType', models.TextField(db_column='contactType', default='Отсутствует', verbose_name='contactType')),
                ('contactValue', models.TextField(db_column='contactValue', default='Отсутствует', verbose_name='contactValue')),
                ('isModerated', models.BooleanField(blank=True, db_column='isModerated', null=True, verbose_name='isModerated')),
                ('isPreferred', models.BooleanField(blank=True, db_column='isPreferred', null=True, verbose_name='isPreferred')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacansy',
            },
        ),
    ]
