# Generated by Django 6.0.2 on 2026-02-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskVacansyController', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacansy',
            name='codeProfessionalSphere',
            field=models.TextField(db_column='codeProfessionalSphere', default='Отсутствует', verbose_name='codeProfessionalSphere'),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='id',
            field=models.TextField(db_column='id', primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='professionalSphereName',
            field=models.TextField(db_column='professionalSphereName', default='Отсутствует', verbose_name='professionalSphereName'),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='salary',
            field=models.TextField(db_column='salary', default='Отсутствует', verbose_name='salary'),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='stateRegionCode',
            field=models.TextField(db_column='stateRegionCode', default='Отсутствует', verbose_name='stateRegionCode'),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='vacancyAddress',
            field=models.TextField(db_column='vacancyAddress', default='Отсутствует', verbose_name='vacancyAddress'),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='vacancyAddressAdditionalInfo',
            field=models.TextField(db_column='vacancyAddressAdditionalInfo', default='Отсутствует', verbose_name='vacancyAddressAdditionalInfo'),
        ),
        migrations.AlterField(
            model_name='vacansy',
            name='vacancyName',
            field=models.TextField(db_column='vacancyName', default='Отсутствует', verbose_name='vacancyName'),
        ),
    ]
