# Generated by Django 6.0.2 on 2026-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskVacansyController', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts',
            name='work_place',
        ),
        migrations.AddField(
            model_name='districts',
            name='work_places',
            field=models.BigIntegerField(default=0, verbose_name='Кол-во рабочих мест'),
        ),
    ]
