# Generated by Django 6.0.2 on 2026-05-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskVacansyController', '0002_alter_vacansy_codeprofessionalsphere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFromMaxMiniApp',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Id пользователя')),
                ('start_use_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала пользования MiniApp')),
            ],
            options={
                'verbose_name': 'Пользователь Mini App в Max',
                'verbose_name_plural': 'Пользователи Mini App в Max',
                'db_table': 'users_from_mini_app_max',
            },
        ),
        migrations.CreateModel(
            name='FavoriteVacansy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskVacansyController.vacansy', verbose_name='Избранная вакансия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskVacansyController.userfrommaxminiapp', verbose_name='Пользователь Mini App в Max')),
            ],
            options={
                'verbose_name': 'Вакансия в изрбанном у пользователя',
                'verbose_name_plural': 'Вакансии в избранном у пользователей',
                'db_table': 'vacancy_in_favorite',
            },
        ),
    ]
