# Generated by Django 6.0.2 on 2026-05-30 12:22

import django.core.validators
import django.db.models.deletion
import kioskVacansyController.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskVacansyController', '0003_userfrommaxminiapp_favoritevacansy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxUserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование резюме')),
                ('file', models.FileField(upload_to=kioskVacansyController.models.user_resume_upload_path_with_date, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Резюме пользователя')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskVacansyController.userfrommaxminiapp', verbose_name='Пользователь MAX Mini App')),
            ],
            options={
                'verbose_name': 'Резюме пользоваетля Max Mini App',
                'verbose_name_plural': 'Резюме пользователя Max Mini App',
                'db_table': 'users_resume_from_mini_app_max',
            },
        ),
        migrations.CreateModel(
            name='VacancyResponseFromUserMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('vacancy_id', models.TextField(verbose_name='id вакансии из базы РостТруда')),
                ('vacancy_url', models.URLField(verbose_name='URL вакансии Работа России')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskVacansyController.maxuserresume', verbose_name='Резюме пользователя')),
            ],
            options={
                'verbose_name': 'Отклик пользователя Max Mini App',
                'verbose_name_plural': 'Отклики пользователей Max Mini App',
                'db_table': 'vacancy_response_from_mini_app_max',
            },
        ),
    ]
