# Generated by Django 6.0.2 on 2026-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskVacansyController', '0004_maxuserresume_vacancyresponsefromusermax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritevacansy',
            name='vacancy',
            field=models.CharField(max_length=512, verbose_name='id Избарнной вакансии'),
        ),
    ]
