FROM kiosk-czn-django-api:v2.0

#установка зависимостей
COPY . .

# Проверяем что файл скопировался
RUN ls -la start.dev.sh

# Меняем формат файла на Unix (на всякий случай)
RUN sed -i 's/\r$//' start.dev.sh

RUN chmod -R 777 ./start.dev.sh

ENTRYPOINT ["/bin/sh", "-c", "sleep 20 && ./start.dev.sh"]

EXPOSE 8000