# Generated by Django 6.0.2 on 2026-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YandexAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('key', models.TextField(help_text='Ключ получить можно с https://developer.tech.yandex.ru/', verbose_name='API ключ')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Yandex API ключ',
                'verbose_name_plural': 'Yandex API ключи',
            },
        ),
    ]
