# Generated by Django 6.0.2 on 2026-03-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.PositiveIntegerField(default=0, help_text='Изменяется при несовместимых изменениях', verbose_name='major')),
                ('minor', models.PositiveIntegerField(default=0, help_text='Изменяется при совместимом добавлении функционала', verbose_name='minor')),
                ('patch', models.PositiveIntegerField(default=0, help_text='Изменяется при совместимом исправлении ошибок', verbose_name='patch')),
                ('dev', models.BooleanField(default=False, help_text='Самая ранняя стадия, возможны ошибки.', verbose_name='Версия в разработке')),
                ('alpha', models.BooleanField(default=False, help_text='Функционал функционален, но не тестирован до конца, содержит баги.', verbose_name='Альфа-версия')),
                ('beta', models.BooleanField(default=False, help_text='Протестирована, функционал заморожен, идет поиск мелких ошибок.', verbose_name='Бета-версия')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Версия киоска',
                'verbose_name_plural': 'Версия киоска',
            },
        ),
    ]
