# Generated by Django 6.0.2 on 2026-02-14 22:00

import datetime
import django.db.models.deletion
import kioskController.models.api_key
import kioskController.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('api_key', models.CharField(default=kioskController.models.api_key.generate_api_key, max_length=128, verbose_name='API ключ')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'API ключ',
                'verbose_name_plural': 'API ключи',
                'db_table': 'api_key',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Игра КЦ',
                'verbose_name_plural': 'Игры КЦ',
            },
        ),
        migrations.CreateModel(
            name='InfoMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('file', models.FileField(upload_to='info_materials/', verbose_name='Файл информационного материала')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Информационный материал КЦ',
                'verbose_name_plural': 'Информационные материалы КЦ',
                'db_table': 'info_material',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Наименование')),
                ('url_path', models.CharField(unique=True, verbose_name='Наименование url пути')),
                ('id_parsing', models.IntegerField(unique=True, verbose_name='Id идентификации КЦ в телефонном справочнике')),
            ],
            options={
                'verbose_name': 'Кадровый центр',
                'verbose_name_plural': 'Кадровые центры',
                'db_table': 'pc',
            },
        ),
        migrations.CreateModel(
            name='PCParentOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вышестоящая организация',
                'verbose_name_plural': 'Вышестоящие организации',
                'db_table': 'pc_parent_organization',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Наименование')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Должность КЦ',
                'verbose_name_plural': 'Должности КЦ',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга КЦ',
                'verbose_name_plural': 'Услуги КЦ',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='GameVisibleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус отображения')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.game', verbose_name='Игра')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Статус отображения игры в КЦ',
                'verbose_name_plural': 'Статусы отображения игр в КЦ',
                'db_table': 'game_visible_status',
            },
        ),
        migrations.CreateModel(
            name='GameUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='Ссылка на игру')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.game', verbose_name='Игра')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Ссылка на игру для КЦ',
                'verbose_name_plural': 'Ссылки на игру для КЦ',
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этажа')),
                ('building_img', models.ImageField(upload_to='floor_imgs/', verbose_name='Схема этажа')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Этаж КЦ',
                'verbose_name_plural': 'Этажи КЦ',
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date_start', models.DateField(default=kioskController.models.event.get_datetime_now, verbose_name='Дата начала')),
                ('time_start', models.TimeField(default=kioskController.models.event.get_datetime_now, verbose_name='Время начала')),
                ('date_end', models.DateField(default=kioskController.models.event.get_datetime_next, verbose_name='Дата окончания')),
                ('time_end', models.TimeField(default=kioskController.models.event.get_datetime_next, verbose_name='Время окончания')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Мероприятие в КЦ',
                'verbose_name_plural': 'Мероприятия в КЦ',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('visible', models.BooleanField(default=False, verbose_name='Статус отображения')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Отдел кадрового центра',
                'verbose_name_plural': 'Отделы кадровых центров',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='PCAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, verbose_name='Адреса КЦ')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Адрес КЦ',
                'verbose_name_plural': 'Адреса КЦ',
                'db_table': 'pc_address',
            },
        ),
        migrations.CreateModel(
            name='PCEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Электронная почта КЦ',
                'verbose_name_plural': 'Электронные почты КЦ',
                'db_table': 'pc_email',
            },
        ),
        migrations.CreateModel(
            name='PCHeadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pc_head_info/', verbose_name='Фото руководителя КЦ')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Руководитель КЦ',
                'verbose_name_plural': 'Руководители КЦ',
                'db_table': 'pc_head_info',
            },
        ),
        migrations.CreateModel(
            name='PCHeadInfoPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телфона')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('pc_head_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pcheadinfo', verbose_name='Информация о руководителе КЦ')),
            ],
            options={
                'verbose_name': 'Номер телефона руководителя КЦ',
                'verbose_name_plural': 'Номера телефонов руководителей КЦ',
                'db_table': 'pc_head_info_phone',
            },
        ),
        migrations.CreateModel(
            name='PCHeadInfoTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(default=datetime.datetime.now, verbose_name='Время начала приема')),
                ('end_time', models.TimeField(default=datetime.datetime.now, verbose_name='Время окончания приема')),
                ('pc_head_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pcheadinfo', verbose_name='Информация о руководителе КЦ')),
            ],
            options={
                'verbose_name': 'Часы приема руководителя КЦ',
                'verbose_name_plural': 'Часы приемов руководителей КЦ',
                'db_table': 'pc_head_info_time_table',
            },
        ),
        migrations.AddField(
            model_name='pc',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kioskController.pcparentorganization', verbose_name='Вышестоящая организация'),
        ),
        migrations.CreateModel(
            name='PCParentOrganizationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pcparentorganization', verbose_name='Вышестоящая организация')),
            ],
            options={
                'verbose_name': 'Адрес вышестоящий организации',
                'verbose_name_plural': 'Адреса вышестоящих организаций',
                'db_table': 'pc_parent_organization_address',
            },
        ),
        migrations.CreateModel(
            name='PCParentOrganizationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pcparentorganization', verbose_name='Вышестоящая организация')),
            ],
            options={
                'verbose_name': 'Электроный адрес',
                'verbose_name_plural': 'Элктронные адреса выщестоящих организаций',
                'db_table': 'pc_parent_organization_email',
            },
        ),
        migrations.CreateModel(
            name='PCParentOrganizationPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128, verbose_name='Номер телефона')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pcparentorganization', verbose_name='Вышестоящая организация')),
            ],
            options={
                'verbose_name': 'Номер телефона вышестоящей организации',
                'verbose_name_plural': 'Номера телефонов вышестоящих организаций',
                'db_table': 'pc_parent_organization_phone',
            },
        ),
        migrations.CreateModel(
            name='PCPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
                'db_table': 'pc_phone',
            },
        ),
        migrations.CreateModel(
            name='PCSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование')),
                ('url', models.CharField(max_length=256, verbose_name='Ссылка на сайт')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('qr_code_img', models.ImageField(blank=True, null=True, upload_to='pc_info_qr_codes/', verbose_name='Qr код')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Сайт КЦ',
                'verbose_name_plural': 'Сайты КЦ',
                'db_table': 'pc_sites',
            },
        ),
        migrations.CreateModel(
            name='PCSocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('link', models.CharField(max_length=512, verbose_name='Ссылка на группу в соц. сети')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='social_networks/', verbose_name='QR code')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Информация о социальной сети КЦ',
                'verbose_name_plural': 'Информация о социальных сетях КЦ',
                'db_table': 'pc_social_networks',
            },
        ),
        migrations.CreateModel(
            name='PCTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0, verbose_name='День недели')),
                ('day_off', models.BooleanField(default=False, verbose_name='Выходной день')),
                ('time_start', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Время начала рабочего дня')),
                ('time_end', models.TimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Время окончания рабочего дня')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Расписание КЦ',
                'verbose_name_plural': 'Расписания КЦ',
                'db_table': 'pc_time_table',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('vector_info', models.TextField(blank=True, null=True, verbose_name='Векторная карта')),
                ('visible', models.BooleanField(blank=True, default=False, verbose_name='Статус отображения')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kioskController.floor', verbose_name='Этаж кабинета')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Комнаты КЦ',
                'verbose_name_plural': 'Комнаты КЦ',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id сотрудника в телефонном справочнике')),
                ('fio', models.CharField(max_length=512, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер телефона')),
                ('date_get_info', models.DateField(auto_now=True, verbose_name='Дата обновления информации')),
                ('absent', models.BooleanField(default=False, verbose_name='Статус отсутствия')),
                ('email', models.CharField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kioskController.room', verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Сотрудник КЦ',
                'verbose_name_plural': 'Сотрудники КЦ',
                'db_table': 'worker',
            },
        ),
        migrations.AddField(
            model_name='pcheadinfo',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.worker', verbose_name='Сотрудник КЦ'),
        ),
        migrations.CreateModel(
            name='WorkerInDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_dep', models.BooleanField(default=False, verbose_name='Глава отдела')),
                ('visible', models.BooleanField(default=True, verbose_name='Статус отображения')),
                ('date_get_info', models.DateField(auto_now=True, verbose_name='Дата обновления информации')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.department', verbose_name='Отдел')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kioskController.post', verbose_name='Должность в отделе')),
                ('services', models.ManyToManyField(blank=True, to='kioskController.service', verbose_name='Услуги сотрудника')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник отдела КЦ',
                'verbose_name_plural': 'Сотрудники отделов КЦ',
                'db_table': 'worker_in_department',
            },
        ),
    ]
