# Generated by Django 6.0.2 on 2026-02-23 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskController', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCHeadInfoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта рукводителя')),
                ('priority', models.PositiveIntegerField(default=999, verbose_name='Порядок отображения')),
                ('pc_head_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pcheadinfo', verbose_name='Информация о руководителе КЦ')),
            ],
            options={
                'verbose_name': 'Email руководителя КЦ',
                'verbose_name_plural': 'Email руководителей КЦ',
                'db_table': 'pc_head_info_email',
            },
        ),
    ]
