# Generated by Django 6.0.2 on 2026-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskController', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='games_screen/', verbose_name='Заставка для игры'),
        ),
    ]
