# Generated by Django 6.0.2 on 2026-02-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kioskController', '0002_pcheadinfoemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcemail',
            options={'verbose_name': 'Email КЦ', 'verbose_name_plural': 'Email КЦ'},
        ),
        migrations.AlterModelOptions(
            name='pcparentorganizationemail',
            options={'verbose_name': 'Email вышестоящей организации', 'verbose_name_plural': 'Email вышестоящих организаций'},
        ),
        migrations.AddField(
            model_name='pc',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Управляющий центр'),
        ),
        migrations.CreateModel(
            name='ShowDepartmentInOtherPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.department', verbose_name='Отдел')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kioskController.pc', verbose_name='Кадровый центр')),
            ],
            options={
                'verbose_name': 'Отображение отдела в другом КЦ',
                'verbose_name_plural': 'Отображения отделов в других КЦ',
                'db_table': 'show_depratment_in_other_pc',
            },
        ),
    ]
