FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /home/app/smart-assistent

# Настройки безопасности
RUN chmod -R 755 /usr/share/nginx/html &&\
    chmod -R 755 /home/app/smart-assistent

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]