# Generated by Django 6.0.2 on 2026-06-06 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kioskVacansyController', '0004_maxuserresume_vacancyresponsefromusermax'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование пререгистрации')),
                ('show', models.BooleanField(default=True, verbose_name='Отображение на сайте')),
                ('pre_registration_code', models.CharField(max_length=256, verbose_name='Код пререгистрации')),
                ('czn_code', models.CharField(max_length=128, unique=True, verbose_name='Код отделения')),
                ('ip_addr', models.CharField(max_length=128, verbose_name='Ip addr сервера очереди')),
                ('port', models.PositiveIntegerField(verbose_name='Порт сервера очереди')),
                ('prioritet', models.PositiveIntegerField(default=999, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Пререгистрация',
                'verbose_name_plural': 'Пререгистрации',
                'db_table': 'pre_registration',
            },
        ),
        migrations.CreateModel(
            name='PreRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.BooleanField(default=False, verbose_name='Статус ошибки')),
                ('content', models.TextField(verbose_name='Содержание лога')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата лога')),
                ('pre_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.preregistration', verbose_name='Пререгистрация')),
            ],
            options={
                'verbose_name': 'Лог пререгистрации',
                'verbose_name_plural': 'Логи пререгистрации',
                'db_table': 'pre_registration_log',
            },
        ),
        migrations.CreateModel(
            name='PreRegistrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время записи')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email записавашегоса')),
                ('code', models.BigIntegerField(blank=True, null=True, verbose_name='Код пререгистрации')),
                ('max_user', models.ForeignKey(blank=True, help_text='Данное поле нужно если пользователь записывался через Mini App в максе', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kioskVacansyController.userfrommaxminiapp', verbose_name='Пользователь с MAX')),
                ('pre_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pre_registration.preregistration', verbose_name='Пререгистрация')),
            ],
            options={
                'verbose_name': 'Запись на пререгистрацию',
                'verbose_name_plural': 'Записи на пререгистрации',
                'db_table': 'pre_registration_record',
            },
        ),
    ]
