# Generated by Django 6.0.2 on 2026-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='address',
            field=models.TextField(default='Адрес', verbose_name='Адрес'),
        ),
    ]
